alias ls="ls -hF --color=auto"
alias ll="ls -lahF --color=auto"
alias lsl="ls -lhF --color=auto"

alias ".."="cd ../"
alias "cd.."="cd ../"

alias mkdir="mkdir -p"

alias cp="cp -r"

alias v="vim"
alias vi="vim"

alias g="git"
alias ga="git add"
alias gaa="git add --all"
alias gb="git branch"
alias gc="git commit -v"
alias gc!="git commit -v --amend"
alias gs="git status"
alias gss="git status --short"
alias gd="git diff"
alias gdw="git diff --word-diff"
alias gf="git fetch"
alias gfa="git fetch --all --prune"
alias gm="git merge"
alias gr="git rebase"
alias gp="git push"
alias ggf="git push --force"
alias gl="git pull"
alias gu="git unstage"
alias gg="git graph"
alias gco="git checkout"
alias gcs="git commit -S"
alias gcl="git clone --recursive"
alias glog="git log --graph --pretty='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"
